#! /usr/bin/env python

import sys
import vtk

if len(sys.argv) < 3:
  print "Usage:"
  print "  %s <binary file> <ascii file>" % sys.argv[0]
  sys.exit()

binary = sys.argv[1]
ascii = sys.argv[2]

r = vtk.vtkDataSetReader()
r.SetFileName(binary)
w = vtk.vtkDataSetWriter()
w.SetInput(r.GetOutput())
w.SetFileName(ascii)
w.Write()
